#!/usr/bin/with-contenv sh

cd /app/node_modules/shout || exit

if [ $SHOUT_PRIVATE == Y ] || [ $SHOUT_PRIVATE == y ] || [ $SHOUT_PRIVATE == Yes ] || [ $SHOUT_PRIVATE == yes ] || [ $SHOUT_PRIVATE == YES ]
then
	exec \
		s6-setuidgid abc node index.js --private --home /config
else
	exec \
		s6-setuidgid abc node index.js --home /config
fi
