#!/usr/bin/with-contenv bash

echo '
******************************************************
******************************************************
*                                                    *
*                                                    *
*          This image has been deprecated            *
*                                                    *
*    It will no longer recieve security updates      *
*                                                    *
*       We recommend TheLounge as a replacement      *
*                                                    *
*    https://hub.docker.com/r/linuxserver/thelounge  *
*                                                    *
*   https://github.com/linuxserver/docker-thelounge  *
*                                                    *
*                                                    *
*                                                    *
******************************************************
******************************************************'
